### PR TITLE
OSX ARM migration.

### PR DESCRIPTION
**Pull request by vincentmr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
Not exactly sure how you enabled the osx build for arm, it should have involved adding some keys to the `conda-forge.yml` file.

There is a migration bot which handles enabling that build environment for this feedstock. You just have to open a PR to add this package [to this text file](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt). You'll still have to manually update the build script and recipe, but the feedstock infrastructure will be correctly configured.

Ideally, if you're trying to enable this build, you have a local arm-osx machine that you can use to debug the build script.

**Comment by vincentmr** [comment]
Hi @carterbox , I followed the instructions given in the [conda-forge doc](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock). Is that redundant with [this text file](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt)? 

I would like to build [PennyLane](https://github.com/conda-forge/pennylane-feedstock) with Conda-Forge's Kokkos and [Kokkos-kernels](https://github.com/conda-forge/kokkos-kernels-feedstock). We can currently build PennyLane for osx-arm64, which includes Kokkos and Kokkos-kernels (SERIAL backend only however) through CMake. @leofang tested on a local machine that the build works and can run some code, but I have to say I don't have directly access to an osx-arm machine. I thus wanted to start migrating Kokkos and Kokkos-kernels to support osx-arm to maintain support on all platforms for PennyLane. 

In commit [7f184f6](https://github.com/conda-forge/kokkos-feedstock/pull/10/commits/7f184f6040296244c2bf479e878119f6462ca2bd) it seems everything compiled fine, but the tests failed because the CPU type is incorrect. I was thus trying to turn testing off in the osx-arm64 case. Could you suggest a clean way to do it (for example `# [not osx-arm64]` or something like that)?

**Comment by carterbox** [comment]
> I followed the instructions given in the [conda-forge doc](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock). Is that redundant with [this text file](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt)?

The text file is mentioned in the blog post you have linked:

> All the below changes will be done by a bot and the packages the bot will send PRs to is determined by the list of packages at [conda-forge-pinning](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt) and their dependences. If you would like to add support, please send a PR adding the feedstock name to the above list. After that PR is merged, you can monitor the status at [conda-forge status-page](https://conda-forge.org/status/#armosxaddition) and if a particular PR is stalled you can send a PR to the feedstock to fix it.

Please let the bot start this PR because some steps from the blog post are missing from your PR, and there may have been additional undocumented steps added to the migration process since 2020-10.

**Comment by vincentmr** [comment]
> Please let the bot start this PR because some steps from the blog post are missing from your PR, and there may have been additional undocumented steps added to the migration process since 2020-10.

Thanks for pointing this out. I went over the first and most relevant paragraph too quickly.

**Comment by vincentmr** [comment]
Also, any chance we could have a Kokkos-3.7.01 osx-arm64 build? Or will migration only work for the latest release?

**Comment by leofang** [comment]
The migrator would only work for the latest release. What we need now is 
- @conda-forge/kokkos to create a new branch based on the migrated `main`
- rebuild 3.7.01 on the new branch

This way we can maintain two versions. I'd suggest @vincentmr to join as maintainer (just open an empty issue with the command `@conda-forge-admin, please add user @vincentmr` and the bot would open a PR) so that you have access do the work 🙂 Happy to help review.

**Comment by vincentmr** [comment]
> This way we can maintain two versions. I'd suggest @vincentmr to join as maintainer (just open an empty issue with the title `@conda-forge-admin, please add user @vincentmr` and the bot would open a PR) so that you have access do the work  Happy to help review.

Do you mean I, or the current maintainers have to `@conda-forge-admin, please add user @vincentmr` ?

**Comment by leofang** [comment]
You can do that.

**Comment by leofang** [comment]
It seems Daniel has done that for you 🙂 https://github.com/conda-forge/kokkos-feedstock/pull/14

**Pull request closed without merging**
