### PR TITLE
REL: Backport osx-arm build to version 3.7

### PR DESCRIPTION
**Pull request by carterbox**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
It seems `libkokkossimd` is new to v4.0 and the test should be removed for v3.x

**Comment by leofang** [comment]
(cc: @vincentmr for vis)

**Comment by vincentmr** [comment]
> It seems `libkokkossimd` is new to v4.0 and the test should be removed for v3.x

Yep, it used to be in [simd-math](https://github.com/kokkos/simd-math).

**Review by vincentmr — APPROVED** [review]
Looks good. Thanks @carterbox

**Pull request merged**
